Repository VultureProject/darwin-client-python, pull requests merged in 2019-07, with the labels that each got.

#2 Add event ID to Darwin header
  darwin/darwinprotocol.py
Labels: enhancement

#4 Fix PEP8 syntax & minor bugs
  darwin/darwinapi.py
  darwin/darwinexceptions.py
  darwin/darwinprotocol.py
Labels: bug, enhancement

#5 Fix comments and version
  darwin/__init__.py
  darwin/darwinapi.py
  darwin/darwinexceptions.py
  darwin/darwinprotocol.py
  darwin/examples.py
  setup.py
Labels: documentation, enhancement

#7 Add tests
  tests/README.md
  tests/__init__.py
  tests/requirements.txt
  tests/run_tests.py
  tests/tests_descr.py
Labels: enhancement

#6 Add filter code
  darwin/darwinapi.py
Labels: enhancement

#8 Add missing socket_type
  tests/run_tests.py
Labels: bug
